name: Build APK
on: [pull_request, push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build the app
        run: ./gradlew assembleRelease

      - name: Upload debug apk
        uses: actions/upload-artifact@v3

        with:
          name: apk-release
          path: app/build/outputs/apk/release
